# Generated by Django 6.0.3 on 2026-07-15 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название привычки')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание привычки')),
                ('color', models.CharField(max_length=7, verbose_name='Цвет привычки')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('frequency', models.JSONField(help_text='\n        Форматы:\n        - Ежедневно: {"type": "daily", "interval": 1}\n        - Через день: {"type": "daily", "interval": 2}\n        - Еженедельно: {"type": "weekly", "days": [1, 3, 5]}  # 1-Пн...7-Вс\n        - Ежемесячно: {"type": "monthly", "day": 15}  # 15-е число\n        ', verbose_name='Настройки периодичности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
