# Generated by Django 6.0.3 on 2026-07-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habbit',
            name='last_executed',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего выполнения'),
        ),
    ]
