# Generated by Django 6.0.3 on 2026-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0002_habbit_last_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='habbit',
            name='count',
            field=models.IntegerField(default=0, verbose_name='кол-во выполнений подряд'),
        ),
    ]
